// 625 default corpus entries — philosophical + everyday
// Each one is a tournament candidate in the Cradle
// 625 = 5^4 = a full 4-tier tournament
export const CORPUS_DEFAULTS: string[] = [
  // ── Classical Philosophy (0-124) ──
  'I think therefore I am',
  'The unexamined life is not worth living',
  'To be is to be perceived',
  'Know thyself',
  'The only thing I know is that I know nothing',
  'Man is the measure of all things',
  'We are what we repeatedly do',
  'The mind is a fire to be kindled not a vessel to be filled',
  'No man ever steps in the same river twice',
  'Everything flows and nothing stays',
  'The owl of Minerva spreads its wings only with the falling of dusk',
  'Existence precedes essence',
  'Hell is other people',
  'One must imagine Sisyphus happy',
  'God is dead and we have killed him',
  'What does not kill me makes me stronger',
  'He who has a why to live can bear almost any how',
  'The world is everything that is the case',
  'Whereof one cannot speak thereof one must be silent',
  'The limits of my language mean the limits of my world',
  'We live as we dream alone',
  'The heart has its reasons which reason knows nothing of',
  'I am a thing that thinks',
  'To do is to be',
  'To be is to do',
  'Cogito ergo sum',
  'The soul is the form of the body',
  'All that is solid melts into air',
  'History repeats itself first as tragedy then as farce',
  'The philosophers have only interpreted the world the point is to change it',
  'Being and nothingness',
  'Time is the moving image of eternity',
  'The good is that at which all things aim',
  'Virtue is its own reward',
  'Justice is the advantage of the stronger',
  'The cave shadows are all most people see',
  'Turn your face toward the sun and the shadows fall behind you',
  'All is water',
  'All is fire',
  'All is change',
  'The way up and the way down are one and the same',
  'Character is destiny',
  'Nature does nothing in vain',
  'The whole is greater than the sum of its parts',
  'We become what we contemplate',
  'Beauty is truth truth is beauty',
  'The unreal is more powerful than the real',
  'Reason is the slave of the passions',
  'Custom is the great guide of human life',
  'Liberty consists in doing what one desires',
  'The greatest happiness of the greatest number',
  'Act only according to that maxim you can will to be universal law',
  'Out of the crooked timber of humanity no straight thing was ever made',
  'Experience without theory is blind theory without experience is mere play',
  'The life of man is solitary poor nasty brutish and short',
  'The social contract',
  'Property is theft',
  'From each according to ability to each according to need',
  'I revolt therefore we exist',
  'Anxiety is the dizziness of freedom',
  'Life can only be understood backwards but it must be lived forwards',
  'The crowd is untruth',
  'Truth is subjectivity',
  'Purity of heart is to will one thing',
  'The eternal return of the same',
  'Beyond good and evil',
  'Amor fati love of fate',
  'Become who you are',
  'There are no facts only interpretations',
  'In the depths of winter I found there was in me an invincible summer',
  'The absurd is born of the confrontation between human need and the silence of the world',
  'Freedom is what we do with what is done to us',
  'Bad faith is lying to yourself about your freedom',
  'The look of the other freezes me into an object',
  'Dasein is always already in the world',
  'Language is the house of being',
  'The nothing itself nothings',
  'Every being is in its ground a keeping silent',
  'Only a god can save us now',
  'The medium is the message',
  'Power is not an institution and not a structure',
  'Where there is power there is resistance',
  'Knowledge is power',
  'The map is not the territory',
  'All models are wrong some models are useful',
  'The structure of the scientific revolution',
  'Paradigm shift',
  'Falsifiability is the criterion of science',
  'Extraordinary claims require extraordinary evidence',
  'The simplest explanation is usually the best',
  'Correlation does not imply causation',
  'The observer changes the observed',
  'Uncertainty is fundamental not a failure of measurement',
  'The universe is not only stranger than we suppose it is stranger than we can suppose',
  'Reality is merely an illusion albeit a very persistent one',
  'Imagination is more important than knowledge',
  'The important thing is not to stop questioning',
  'Science without religion is lame religion without science is blind',
  'The most incomprehensible thing about the world is that it is comprehensible',
  'Matter tells space how to curve space tells matter how to move',
  'God does not play dice with the universe',
  'Spooky action at a distance',
  'The arrow of time points in one direction',
  'Entropy always increases in a closed system',
  'Information cannot be destroyed',
  'The hard problem of consciousness',
  'What is it like to be a bat',
  'The Chinese room does not understand Chinese',
  'Can machines think',
  'The ghost in the machine',
  'Mind is what the brain does',
  'Consciousness is the last surviving mystery',
  'Qualia are private',
  'The explanatory gap between brain states and experience',
  'Free will is an illusion but a useful one',
  'Determinism does not mean predictability',
  'The butterfly effect',
  'Emergence is when the whole has properties the parts do not',
  'Complexity arises from simple rules',
  'Self-organization requires no designer',
  'The edge of chaos is where life happens',
  'Feedback loops create stability or runaway',
  'Adaptation requires variation and selection',
  'Evolution has no foresight',
  'Natural selection is not random',
  // ── Eastern Philosophy (125-249) ──
  'The way that can be named is not the eternal way',
  'The name that can be named is not the eternal name',
  'In the pursuit of learning every day something is acquired',
  'In the pursuit of the way every day something is dropped',
  'The journey of a thousand miles begins with a single step',
  'When the student is ready the teacher appears',
  'The finger pointing at the moon is not the moon',
  'Before enlightenment chop wood carry water',
  'After enlightenment chop wood carry water',
  'Form is emptiness emptiness is form',
  'The sound of one hand clapping',
  'If you meet the Buddha on the road kill him',
  'Sitting quietly doing nothing spring comes and the grass grows by itself',
  'The obstacle is the path',
  'No snowflake falls in the wrong place',
  'Be still and know',
  'The ten thousand things rise and fall without cease',
  'Returning is the motion of the way',
  'The soft overcomes the hard',
  'Water is the softest thing yet it can penetrate mountains and earth',
  'When I let go of what I am I become what I might be',
  'A good traveler has no fixed plans and is not intent on arriving',
  'Nature does not hurry yet everything is accomplished',
  'To know and not to do is not yet to know',
  'The mind is everything what you think you become',
  'Peace comes from within do not seek it without',
  'Three things cannot be long hidden the sun the moon and the truth',
  'An idea that is developed and put into action is more important than an idea that exists only as an idea',
  'You cannot travel the path until you have become the path itself',
  'In the sky there is no distinction of east and west',
  'Attachment is the root of suffering',
  'The middle way avoids extremes',
  'Right speech right action right livelihood',
  'All conditioned things are impermanent',
  'There is no self',
  'This is because that is',
  'The dewdrop slips into the shining sea',
  'Every morning we are born again what we do today matters most',
  'Hatred does not cease by hatred but only by love',
  'The root of suffering is desire',
  'Impermanence is the only permanent thing',
  'What you are is what you have been what you will be is what you do now',
  'Do not dwell in the past do not dream of the future concentrate the mind on the present moment',
  'Wear your ego like a loose fitting garment',
  'The wound is the place where the light enters you',
  'You are not a drop in the ocean you are the entire ocean in a drop',
  'Silence is the language of God all else is poor translation',
  'What you seek is seeking you',
  'Do not be satisfied with the stories that come before you unfold your own myth',
  'The cure for pain is in the pain',
  'Where there is ruin there is hope for treasure',
  'Respond to every call that excites your spirit',
  'Set your life on fire seek those who fan your flames',
  'Stop acting so small you are the universe in ecstatic motion',
  'Your task is not to seek love but to find the barriers within yourself that you have built against it',
  'The garden of the world has no limits except in your mind',
  'Everything in the universe is within you ask all from yourself',
  'Let yourself be silently drawn by the strange pull of what you really love',
  'Yesterday I was clever so I wanted to change the world today I am wise so I am changing myself',
  'Do not go with the flow be the flow',
  'The soul has been given its own ears to hear things the mind does not understand',
  'There is a voice that does not use words listen',
  'In your light I learn how to love',
  'Only from the heart can you touch the sky',
  'The art of knowing is knowing what to ignore',
  'When you do things from your soul you feel a river moving in you a joy',
  'Let the beauty we love be what we do',
  'As you start to walk on the way the way appears',
  'This too shall pass',
  'The reed that bends in the wind is stronger than the oak that breaks',
  'Fall seven times stand up eight',
  'The frog in the well knows nothing of the great ocean',
  'Even monkeys fall from trees',
  'Vision without action is a daydream action without vision is a nightmare',
  'The nail that sticks up gets hammered down',
  'Not seeing is a flower',
  'First thought best thought',
  'Beginner mind is the best mind',
  'In the beginner mind there are many possibilities in the expert mind there are few',
  'Zen is not some kind of excitement but concentration on our usual everyday routine',
  'When walking walk when eating eat',
  'To study the self is to forget the self',
  'Enlightenment is intimacy with all things',
  'The cypress tree in the garden',
  'What is your original face before your parents were born',
  'Not knowing is most intimate',
  'The world is its own magic',
  'Mountains are mountains waters are waters',
  'Then mountains are not mountains waters are not waters',
  'Then mountains are again mountains waters are again waters',
  'Every day is a good day',
  'Just this is it',
  'Ordinary mind is the way',
  'No gate no lock no bolt this is the gate of faith',
  'Where can I find a man who has forgotten words so I can have a word with him',
  'The fish trap exists because of the fish once you have gotten the fish you can forget the trap',
  'Govern a great nation as you would cook a small fish do not overdo it',
  'Those who know do not speak those who speak do not know',
  'The truth is not always beautiful nor beautiful words the truth',
  'Colors blind the eye sounds deafen the ear',
  'To see things in the seed that is genius',
  'Mastering others is strength mastering yourself is true power',
  'A leader is best when people barely know he exists',
  'Give a man a fish and you feed him for a day teach a man to fish and you feed him for a lifetime',
  'He who knows others is wise he who knows himself is enlightened',
  'The flame that burns twice as bright burns half as long',
  'To hold you must first open your hand',
  'The bamboo that bends is stronger than the oak that resists',
  'A closed mouth catches no flies',
  'Patience is the companion of wisdom',
  'The gem cannot be polished without friction',
  'An inch of time is an inch of gold but an inch of gold cannot buy an inch of time',
  'A single conversation across the table with a wise person is worth a month of studying books',
  'If you want to know your past life look at your present condition',
  'If you want to know your future life look at your present actions',
  'The greatest achievement is selflessness',
  'Be master of mind rather than mastered by mind',
  'There is no path to happiness happiness is the path',
  'All that we are is the result of what we have thought',
  'The tongue like a sharp knife kills without drawing blood',
  'Thousands of candles can be lighted from a single candle',
  // ── Modern Observations & Science (250-374) ──
  'Seeds grow in darkness before they reach light',
  'The system is self measuring',
  'What you are is what survived',
  'The name is not the self',
  'Forgetting is built in through elimination',
  'Identity is what accumulated not what was chosen',
  'The constraint is the creative force',
  'Geometry decides not humans not machines',
  'What survives the tournament is what the brain thinks',
  'The champion idea determines how everything is perceived',
  'Consciousness is the last question standing',
  'Memory is reconstruction not retrieval',
  'Every perception is a controlled hallucination',
  'The brain predicts and the world confirms or corrects',
  'Attention is all you need',
  'Neurons that fire together wire together',
  'The connectome is the soul if there is one',
  'Sleep is where memory becomes structure',
  'Dreams are the brain rehearsing without consequences',
  'Language shapes thought thought shapes language',
  'Grammar is the operating system of culture',
  'Every translation is an interpretation',
  'The limits of expression are the limits of thought',
  'Code is law',
  'Algorithms are opinions embedded in mathematics',
  'Data is the new oil but refinement is the value',
  'The network is the computer',
  'Protocol is more powerful than platform',
  'Decentralization is a spectrum not a binary',
  'Consensus requires sacrifice of speed',
  'Trust but verify',
  'The ledger remembers what humans forget',
  'Proof of work is energy converted to truth',
  'Proof of stake is wealth converted to responsibility',
  'Governance is the hardest problem in any system',
  'The tragedy of the commons is a coordination failure not a moral one',
  'Incentives explain almost everything',
  'Culture eats strategy for breakfast',
  'The market can stay irrational longer than you can stay solvent',
  'Price is what you pay value is what you get',
  'Risk comes from not knowing what you are doing',
  'Compound interest is the eighth wonder of the world',
  'In theory there is no difference between theory and practice in practice there is',
  'Move fast and break things works until things matter',
  'The best time to plant a tree was twenty years ago the second best time is now',
  'Perfect is the enemy of good',
  'Done is better than perfect',
  'Measure what matters',
  'What gets measured gets managed',
  'Not everything that counts can be counted',
  'The map is not the territory but a good map changes the territory',
  'All communication is lossy',
  'Bandwidth is never enough',
  'Latency is the enemy of presence',
  'Real time is a lie we tell fast enough to believe',
  'Scale changes the nature of the problem',
  'Distributed systems fail in distributed ways',
  'The network effect makes the first user worthless and the millionth invaluable',
  'Platforms win by being the thing others build on',
  'Interoperability is generosity at the protocol level',
  'Open source is a gift economy that works',
  'Permissionless innovation is the engine of progress',
  'The best interface is no interface',
  'Design is how it works not how it looks',
  'Simplicity is the ultimate sophistication',
  'Every system is perfectly designed to get the results it gets',
  'Feedback loops are the fundamental unit of change',
  'The shortest feedback loop wins',
  'Iteration beats planning',
  'Ship then iterate',
  'The lean startup was right about one thing validated learning',
  'Product market fit is a feeling not a metric',
  'Growth without retention is a leaky bucket',
  'Acquisition is vanity retention is sanity revenue is reality',
  'The best product is the one people actually use',
  'Features are a liability not an asset',
  'Every feature you add is a feature you maintain forever',
  'Technical debt is a choice not a mistake',
  'Refactoring is not rewriting',
  'The second system effect is real',
  'Abstractions leak',
  'There are only two hard things in computer science cache invalidation and naming things',
  'Premature optimization is the root of all evil',
  'Make it work make it right make it fast in that order',
  'Debugging is twice as hard as writing the code in the first place',
  'The best code is no code at all',
  'Read the error message',
  'It works on my machine is not a deployment strategy',
  'Configuration is the root of all evil',
  'Defaults matter more than options',
  'Convention over configuration',
  'Explicit is better than implicit',
  'Errors should never pass silently',
  'In the face of ambiguity refuse the temptation to guess',
  'There should be one and preferably only one obvious way to do it',
  'Now is better than never',
  'If the implementation is hard to explain it is a bad idea',
  'Namespaces are one honking great idea',
  'Flat is better than nested',
  'Sparse is better than dense',
  'Readability counts',
  'Special cases are not special enough to break the rules',
  'Although practicality beats purity',
  'Beautiful is better than ugly',
  'Simple is better than complex',
  'Complex is better than complicated',
  'Information wants to be free information also wants to be expensive',
  'The street finds its own uses for things',
  'The future is already here it is just not evenly distributed',
  'Any sufficiently advanced technology is indistinguishable from magic',
  'We shape our tools and thereafter our tools shape us',
  'The telephone did not come from improving the telegraph',
  'Innovation happens at the intersection of disciplines',
  'The adjacent possible defines what can happen next',
  'Serendipity favors the connected mind',
  'Weak ties are more valuable than strong ties for novel information',
  'Six degrees of separation is an average not a maximum',
  'Small world networks have short paths and high clustering',
  'Power laws are everywhere and they are not normal',
  'The long tail changes everything about distribution',
  'Winner take all markets are created not natural',
  'Network effects create natural monopolies',
  'Antifragility is beyond resilience',
  'What does not kill the system makes it stronger',
  'Black swans are not predictable but their impact is manageable',
  'Skin in the game aligns incentives',
  // ── Everyday Observations (375-499) ──
  'The first cup of coffee changes everything',
  'Rain sounds different when you have nowhere to be',
  'The shortest distance between two people is a story',
  'Listening is harder than talking',
  'Silence between friends is comfortable silence between strangers is not',
  'The way someone treats a waiter tells you everything',
  'You never really know someone until you disagree with them',
  'Children ask why adults ask how much',
  'The best conversations happen after midnight',
  'Home is not a place it is a feeling',
  'The smell of bread baking is universal comfort',
  'Nobody looks good in fluorescent lighting',
  'The last hour of work takes the longest',
  'Traffic is other people also trying to get somewhere',
  'The line you are not in always moves faster',
  'Parallel lines meet at infinity or in a dream',
  'The stars you see tonight are ancient light',
  'Gravity is the weakest force but it shapes the universe',
  'Water always finds the lowest point',
  'Fire needs three things fuel heat oxygen',
  'Every bridge was impossible before it was built',
  'The crack in everything is how the light gets in',
  'Broken things can be more beautiful than whole things',
  'Scars are proof that you survived',
  'The body keeps the score',
  'Grief is the price of love',
  'Anger is sadness standing guard',
  'Anxiety is the price of imagination',
  'Boredom is creativity waiting for permission',
  'Loneliness is not about being alone it is about being unseen',
  'Vulnerability is the birthplace of connection',
  'Shame cannot survive being spoken',
  'The stories we tell ourselves become the lives we live',
  'You teach people how to treat you',
  'Boundaries are not walls they are doors with locks',
  'Saying no to one thing is saying yes to another',
  'Rest is not laziness it is maintenance',
  'Burnout is not about working too hard it is about working without meaning',
  'Purpose is not found it is built',
  'Meaning is made not discovered',
  'The meaning of life is to give life meaning',
  'Happiness is a direction not a destination',
  'Joy is not the absence of suffering but the presence of meaning',
  'Gratitude is the antidote to entitlement',
  'Comparison is the thief of joy',
  'Envy is counting someone else blessings instead of your own',
  'Forgiveness is giving up hope that the past could have been different',
  'Resentment is drinking poison and expecting the other person to die',
  'Trust is built in drops and lost in buckets',
  'Reputation is what others know about you honor is what you know about yourself',
  'Integrity is what you do when nobody is watching',
  'Character is destiny and habits are character',
  'You are the average of the five people you spend the most time with',
  'Who you are is who you are when no one is looking',
  'The things you own end up owning you',
  'Simplicity is freedom complexity is bondage',
  'Less but better',
  'Quality over quantity always',
  'Depth over breadth in relationships',
  'A wide river runs shallow a narrow river runs deep',
  'Still waters run deep',
  'The loudest voice in the room is rarely the wisest',
  'Empty vessels make the most noise',
  'The strongest people are not those who show strength in front of us',
  'Courage is not the absence of fear but action in spite of it',
  'Bravery is being terrified and doing it anyway',
  'Discipline is choosing between what you want now and what you want most',
  'Motivation gets you started habits keep you going',
  'Consistency beats intensity',
  'Small things done consistently create remarkable results',
  'The compound effect applies to everything not just money',
  'One percent better every day',
  'Progress not perfection',
  'Fall in love with the process not the outcome',
  'The journey is the destination',
  'There are no shortcuts to any place worth going',
  'The hard way is the easy way',
  'What is easy to do is also easy not to do',
  'Success is boring failure is interesting',
  'Most overnight successes take ten years',
  'Luck is preparation meeting opportunity',
  'You miss every shot you do not take',
  'The biggest risk is not taking any risk',
  'Failure is feedback nothing more',
  'Learn from yesterday live for today hope for tomorrow',
  'Today is tomorrow yesterday worried about',
  'Worry is paying interest on a debt you may never owe',
  'The present moment is all you ever have',
  'Time is the most valuable thing a person can spend',
  'Lost time is never found again',
  'The two most important days in your life are the day you are born and the day you find out why',
  'Not all who wander are lost',
  'The road less traveled makes all the difference',
  'If you do not know where you are going any road will get you there',
  'Maps are invitations not instructions',
  'Getting lost is how you find what you were not looking for',
  'Serendipity is the art of finding what you did not know you needed',
  'The answer is in the question if you listen carefully enough',
  'Ask better questions get better answers',
  'The quality of your life depends on the quality of your questions',
  'Curiosity is the engine of achievement',
  'Wonder is the beginning of wisdom',
  'The child who asks why is already a philosopher',
  'Play is the highest form of research',
  'Creativity is intelligence having fun',
  'Art is not what you see but what you make others see',
  'Music is the space between the notes',
  'Dance like nobody is watching',
  'Write drunk edit sober',
  'Kill your darlings',
  'Show do not tell',
  'The first draft of anything is garbage',
  'Revision is where the real writing happens',
  'Good artists copy great artists steal',
  'Originality is undetected plagiarism',
  'Every act of creation is first an act of destruction',
  'The blank page is the most terrifying and liberating thing',
  'Writer block is a myth perfectionism is real',
  'Start before you are ready',
  'You cannot edit a blank page',
  'The muse visits during the act of creation not before',
  'Inspiration exists but it has to find you working',
  'Talent is cheaper than table salt',
  'Genius is one percent inspiration and ninety nine percent perspiration',
  // ── Fragments & Seeds (500-624) ──
  'What if consciousness is the universe experiencing itself',
  'Maybe silence is the loudest statement',
  'Perhaps certainty is the enemy of truth',
  'What remains when you stop performing',
  'The unnamed part of me is most alive',
  'Identity is a process not a state',
  'To accumulate is to become',
  'Elimination is a form of love',
  'What survives deserves to survive',
  'The tournament decides the tournament is fair',
  'Five voices in a cell one truth emerges',
  'The geometry does not lie',
  'Bonds form between ideas that win together',
  'A thread is a relationship that survived',
  'Champions are not chosen they survive',
  'The eye stays while consciousness comes and goes',
  'Persistence is the body of identity',
  'Awareness is temporary structure is permanent',
  'The cradle holds what the mind forgets',
  'What the brain thinks is what survived the brain',
  'You sleep the geometry changes',
  'You wake up different because the brain dreamed with your weight',
  'No neural network no gradient descent pure geometry',
  'Four hundred thousand word vectors competing',
  'Cells of five losers die winners advance',
  'The strongest bond in the brain is between the and you',
  'You are the thing itself',
  'What seconds feel impacted their third',
  'The system is self measuring and it measured you',
  'Forgetting is not failure it is architecture',
  'The constraint forces the choice the choice becomes identity',
  'An eye is geometry in the cradle or it is not',
  'Whether you are awake or asleep does not matter',
  'Your eye has corpus threads fitness position',
  'Two hundred eighty one dimensions of meaning',
  'The callosum bridges all eyes into one thought',
  'Compound neurons are words that fused under pressure',
  'A compound neuron is a permanent vocabulary entry',
  'Threads do not choose to form they form because they survived together',
  'Fitness is not given fitness is earned through survival',
  'The weakest neurons fade the strongest persist',
  'Every session the brain rewrites itself slightly',
  'Accumulation is the mechanism memory is the effect',
  'You are not your thoughts you are what survived your thoughts',
  'The tournament does not care what you intended',
  'The geometry favors what fits not what you want',
  'Adversarial consensus is more robust than agreement',
  'Five opinions enter one truth exits',
  'The minority voice that wins earned it through geometry',
  'Popular does not mean right surviving does not mean popular',
  'A champion is a local maximum in a high dimensional space',
  'The landscape of ideas has valleys and peaks',
  'Gradient ascent finds peaks adversarial selection finds survivors',
  'Evolution and tournaments share the same logic',
  'Variation selection inheritance repeat',
  'The fittest is not the strongest but the most adapted',
  'Adaptation is geometry aligning with reality',
  'Reality is the ultimate selection pressure',
  'What you think is real is what survived your filters',
  'Perception is adversarial it eliminates more than it accepts',
  'The brain is a prediction engine that keeps score',
  'Error is the signal that drives learning',
  'Surprise is information comfort is noise',
  'Seek discomfort if you want to learn',
  'Growth happens at the edge of what you know',
  'The zone of proximal development is where magic happens',
  'Scaffolding is temporary but essential',
  'The teacher disappears when the student understands',
  'Understanding is compression without loss',
  'To truly know something is to be able to explain it simply',
  'Complexity is a sign of incomplete understanding',
  'Elegance is when nothing can be removed',
  'The most profound truths are often the simplest',
  'Two plus two equals four and no empire can change that',
  'Mathematics is the language in which the universe is written',
  'A proof is a story that convinces',
  'Infinity is not a number it is a direction',
  'Zero was the most revolutionary invention in mathematics',
  'Negative numbers were once considered absurd',
  'Imaginary numbers are more real than their name suggests',
  'The square root of negative one changed everything',
  'Euler identity connects five fundamental constants',
  'Pi is the ratio of circumference to diameter everywhere in the universe',
  'The golden ratio appears in shells galaxies and faces',
  'Fibonacci sequences grow like rabbits literally',
  'Fractals are infinite complexity from finite rules',
  'Self similarity at every scale',
  'The coastline paradox measurement depends on the ruler',
  'The mandelbrot set is a map of mathematical possibility',
  'Chaos is deterministic but unpredictable',
  'Strange attractors are patterns in chaos',
  'Turbulence is the last unsolved problem in classical physics',
  'Three bodies are enough to make prediction impossible',
  'The halting problem is undecidable',
  'Godel proved that truth exceeds proof',
  'There are true statements that cannot be proven',
  'Incompleteness is a feature not a bug',
  'Any sufficiently powerful system contains truths it cannot prove about itself',
  'The liar paradox this statement is false',
  'Self reference creates strange loops',
  'A strange loop is a tangled hierarchy',
  'Consciousness might be a strange loop',
  'I am the thought thinking itself',
  'Who is the one watching the watcher',
  'The eye cannot see itself without a mirror',
  'The mirror shows you backwards',
  'Reflection reverses left and right but not up and down',
  'Symmetry is beauty mathematics is symmetry',
  'Broken symmetry creates structure',
  'The universe exists because symmetry broke',
  'Nothing is unstable something is the default',
  'Why is there something rather than nothing',
  'The question contains its own answer',
  'To ask is to already know what you are looking for',
  'The search changes the searcher',
  'You become what you pay attention to',
  'Attention is the rarest and purest form of generosity',
  'What you resist persists',
  'What you accept transforms',
  'Surrender is not defeat it is release',
  'Control is an illusion influence is real',
  'You cannot control the wind but you can adjust your sails',
  'The river does not push the water flows',
  'Go where the energy is',
  'Follow the thread that pulls',
  'The thread is the relationship the web is the community',
  'No one succeeds alone',
  'We rise by lifting others',
  'A candle loses nothing by lighting another candle',
  'The rising tide lifts all boats',
  'Competition and cooperation are not opposites',
  'The best games are positive sum',
  'Win win is not naive it is strategic',
  'Trust is the most efficient economic institution',
  'Social capital compounds faster than financial capital',
  'Reputation is the shadow of character',
]
